### ISSUE TITLE
Creation date extraction

### ISSUE THREAD

**Issue by benel** [Hypertopic/Steatite#8]
In items and attributes API, Dublin Core creation date (`created`) could be extracted on the fly from picture metadata.

As in feature #1, `exiftool` could be used for that.

**Comment by benel** [comment]
A lot of different dates are available from the pictures metadata. This should be the date where the picture was taken. Therefore the date to be chosen is one that isn't provided in digitized paper pictures.

**Comment by Slaals** [comment]
This post concerns this feature and the feature #1 

I used the `exiftool` as suggested, here is the document the user get when /corpus/C is requested : 

```javascript
{"rows":[
  {"key":["Test"], "value":{"name":"Test"}}
, 
    {"key":["Test", "36e5933009da7787c34e3f104f9b4f39e2139379"], "value":{"name":"oiseau"}},
    {"key":["Test", "36e5933009da7787c34e3f104f9b4f39e2139379"], "value":{"resource":"http://localhost/Steatite/picture/36e5933009da7787c34e3f104f9b4f39e2139379"}},
    {"key":["Test", "36e5933009da7787c34e3f104f9b4f39e2139379"], "value":{"thumbnail":"http://localhost/Steatite/thumbnail/36e5933009da7787c34e3f104f9b4f39e2139379"}}
    {"key":["Test", "36e5933009da7787c34e3f104f9b4f39e2139379"], "value":{"date":""}},
    {"key":["Test", "36e5933009da7787c34e3f104f9b4f39e2139379"], "value":{"coverage":""}}
, 
    {"key":["Test", "8d0ea81e3bcaa121e6e44722c5bba4e7d7687ba2"], "value":{"name":"nature"}},
    {"key":["Test", "8d0ea81e3bcaa121e6e44722c5bba4e7d7687ba2"], "value":{"resource":"http://localhost/Steatite/picture/8d0ea81e3bcaa121e6e44722c5bba4e7d7687ba2"}},
    {"key":["Test", "8d0ea81e3bcaa121e6e44722c5bba4e7d7687ba2"], "value":{"thumbnail":"http://localhost/Steatite/thumbnail/8d0ea81e3bcaa121e6e44722c5bba4e7d7687ba2"}}
    {"key":["Test", "8d0ea81e3bcaa121e6e44722c5bba4e7d7687ba2"], "value":{"date":"2015-03-19"}},
    {"key":["Test", "8d0ea81e3bcaa121e6e44722c5bba4e7d7687ba2"], "value":{"coverage":""}}
, 
    {"key":["Test", "bbdd5bc40350f7115d62842780655da62c518c64"], "value":{"name":"street"}},
    {"key":["Test", "bbdd5bc40350f7115d62842780655da62c518c64"], "value":{"resource":"http://localhost/Steatite/picture/bbdd5bc40350f7115d62842780655da62c518c64"}},
    {"key":["Test", "bbdd5bc40350f7115d62842780655da62c518c64"], "value":{"thumbnail":"http://localhost/Steatite/thumbnail/bbdd5bc40350f7115d62842780655da62c518c64"}}
    {"key":["Test", "bbdd5bc40350f7115d62842780655da62c518c64"], "value":{"date":"2015-11-28"}},
    {"key":["Test", "bbdd5bc40350f7115d62842780655da62c518c64"], "value":{"coverage":"48 deg 18' 1.44&quot; N, 4 deg 5' 5.38&quot; E"}}
]}
```
The same goes in case one item is request.

The field `date` is the tag `Date Time Original`. The tag corresponds of the date when the numerical picture was generated, that means (*the moment the photographe has been taken - a very small Delta*). Unfortunately, this field can be undefined as we can see in the document above.
Source : http://exif.org/Exif2-2.PDF

The field `coverage` is the geolocalisation of the picture, it can also be undefined. We have to notice that putting some coordinates is not that useful and is not standardized regarding to [GTI - Thesaurus of Geographic Names](http://www.getty.edu/research/tools/vocabularies/tgn/index.html) which is highly recommended by the standards.

The fields are named accordingly to [Dublin Core standards](http://www.bnf.fr/fr/professionnels/formats_catalogage/a.f_dublin_core.html).

So, I suggest that the next step could be to get the name of the city (or the area) with the coordinates by using [Google Map Geocoding](https://developers.google.com/maps/documentation/geocoding/intro).

**Comment by benel** [comment]
> `Date Time Original`. The tag corresponds to the date when the numerical picture was generated, that means (the moment the photographe has been taken

Indeed. That's the exif metadata we needed.

> geolocation of the picture

You forgot to tell which metadata you used. Considering the sample value you used, I suppose it was `GPS Position`.

> The field `date`

Dublin Core `date` definition is too broad. Another one is far better.

> the next step could be to get the name of the city (or the area) with the coordinates

The city would't be useful in our case. Ideally we would want visitors to locate the stain glass. Since civilian GPS is not very precise, we can at least locate the church containing it.

Geolocation with longitude and latitude seems to be [possible in Dublin Core] (http://wiki.dublincore.org/index.php/User_Guide/Creating_Metadata#Spatial).

**Comment by benel** [comment]
> Unfortunately, this field can be undefined as we can see in the document above.

This is not really problem. But the field shouldn't be shown when it's undefined.
